<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="vi"><head><title>Quản lý sách</title></head><body>
<div class="admin-heading table-heading"><div><span class="eyebrow">DANH MỤC</span><h1>Quản lý sách</h1></div><a class="button primary" href="${pageContext.request.contextPath}/admin/books/create">+ Thêm sách</a></div>
<c:if test="${not empty sessionScope.notice}"><div class="notice success"><c:out value="${sessionScope.notice}"/></div><c:remove var="notice" scope="session"/></c:if>
<div class="table-wrap"><table><thead><tr><th>ID</th><th>Bìa sách</th><th>Tiêu đề</th><th>ISBN</th><th>Nhà xuất bản</th><th>Số lượng</th><th>Thao tác</th></tr></thead><tbody>
<c:forEach items="${books}" var="book"><tr><td>${book.bookId}</td><td><div class="book-thumb"><c:choose><c:when test="${not empty book.coverImage}"><img src="${pageContext.request.contextPath}/<c:out value='${book.coverImage}'/>" alt="Bìa <c:out value='${book.title}'/>"></c:when><c:otherwise>SÁCH</c:otherwise></c:choose></div></td><td><strong><c:out value="${book.title}"/></strong></td><td><c:out value="${book.isbn}"/></td><td><c:out value="${book.publisher}"/></td><td><c:out value="${book.quantity}"/></td><td class="actions"><div class="actions-content"><a href="${pageContext.request.contextPath}/admin/books/edit?id=${book.bookId}">Sửa</a><form action="${pageContext.request.contextPath}/admin/books/delete" method="post"><input type="hidden" name="id" value="${book.bookId}"><button type="submit" onclick="return confirm('Xóa sách này?')">Xóa</button></form></div></td></tr></c:forEach>
</tbody></table></div>
<c:if test="${empty books}"><div class="empty-state"><strong>Chưa có sách</strong><span>Thêm một đầu sách để bắt đầu.</span></div></c:if>
<c:if test="${totalPages > 1}"><nav class="pagination" aria-label="Phân trang sách"><c:choose><c:when test="${page > 1}"><a class="pagination-control" href="${pageContext.request.contextPath}/admin/books?page=${page - 1}">← Trang trước</a></c:when><c:otherwise><span class="pagination-control disabled" aria-disabled="true">← Trang trước</span></c:otherwise></c:choose><c:forEach begin="1" end="${totalPages}" var="number"><a class="${number == page ? 'active' : ''}" href="${pageContext.request.contextPath}/admin/books?page=${number}">${number}</a></c:forEach><c:choose><c:when test="${page < totalPages}"><a class="pagination-control" href="${pageContext.request.contextPath}/admin/books?page=${page + 1}">Trang sau →</a></c:when><c:otherwise><span class="pagination-control disabled" aria-disabled="true">Trang sau →</span></c:otherwise></c:choose></nav></c:if>
</body></html>
